# Generated by Django 4.1.3 on 2022-12-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOTR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='blogs',
        ),
    ]
