# Generated by Django 4.1.3 on 2022-12-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOTR', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='apellido',
            new_name='nombre_del_personaje',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='nombre',
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default='C:\\TOMAS AGOSTINO ALVARENGA\\CODER-HOUSE\\ProyectoFinal\\media\x07vatares\x07vatarDefault.jpg', upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='parrafo',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
